build:
  maxIssues: 0

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
