/*
 * Copyright (c) 2024 Robert Jaros
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package dev.kilua.rpc

import dev.kilua.rpc.types.serializers.DecimalSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.overwriteWith
import java.math.BigDecimal

/**
 * JSON utility functions
 */
public actual object RpcSerialization {

    private val rpcSerializersModule = SerializersModule {
        contextual(BigDecimal::class, DecimalSerializer)
        contextual(Result::class) { args -> ResultSerializer(args[0]) }
    }

    /**
     * Default Json configuration for the fullstack interfaces.
     */
    public actual val plain: Json = Json {
        ignoreUnknownKeys = true
        serializersModule = rpcSerializersModule
    }

    /**
     * @suppress internal variable
     * Internal serializers module for custom exceptions (generated by the Kilua compiler plugin).
     */
    public actual var exceptionsSerializersModule: SerializersModule? = null

    /**
     * Custom JSON configuration for the fullstack interfaces.
     */
    public actual var customConfiguration: Json? = null

    /**
     * Return customized Json configuration.
     */
    public actual fun getJson(serializersModules: List<SerializersModule>?): Json {
        return if (exceptionsSerializersModule == null && customConfiguration == null && serializersModules == null) {
            plain
        } else {
            Json(from = (customConfiguration ?: Json.Default)) {
                ignoreUnknownKeys = true
                serializersModule = serializersModule.overwriteWith(SerializersModule {
                    this.include(rpcSerializersModule)
                    exceptionsSerializersModule?.let { this.include(it) }
                    serializersModules?.forEach {
                        this.include(it)
                    }
                })
            }
        }
    }
}
